/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package darkinsrevenge;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jam
 */
public class MainMenuFrame extends javax.swing.JPanel {
    Image img;
    /**
     * Creates new form MainMenuFrame
     */
    MainScreen sc;
    Clip c;
   
    boolean enterThread = true;
    public MainMenuFrame(MainScreen sc) {
        
        initComponents();
        try {
            img = ImageIO.read(this.getClass().getResourceAsStream("./Resources/MainMenuSplash.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(MainMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setBackground(Color.black);
        this.sc = sc;
        playBackgroundMusic();
    }
    
    
    
    
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PlayGame = new javax.swing.JLabel();
        Leaderboard = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Darkin's Revenge");

        PlayGame.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PlayGame.setForeground(new java.awt.Color(255, 255, 255));
        PlayGame.setText("Play");
        PlayGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayGameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayGameMouseExited(evt);
            }
        });

        Leaderboard.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Leaderboard.setForeground(new java.awt.Color(255, 255, 255));
        Leaderboard.setText("Leaderboards");
        Leaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeaderboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LeaderboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LeaderboardMouseExited(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Leaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(PlayGame, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(758, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(PlayGame, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Leaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PlayGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayGameMouseClicked
        sc.changeScreen("2");
    }//GEN-LAST:event_PlayGameMouseClicked

    private void PlayGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayGameMouseEntered
        PlayGame.setText("Play <");
        
    }//GEN-LAST:event_PlayGameMouseEntered

    private void PlayGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayGameMouseExited
        PlayGame.setText("Play");
    }//GEN-LAST:event_PlayGameMouseExited

    private void LeaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderboardMouseClicked
       
    }//GEN-LAST:event_LeaderboardMouseClicked

    private void LeaderboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderboardMouseEntered
       Leaderboard.setText("Leaderboards <");
    }//GEN-LAST:event_LeaderboardMouseEntered

    private void LeaderboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderboardMouseExited
        Leaderboard.setText("Leaderboards");
    }//GEN-LAST:event_LeaderboardMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        int res = JOptionPane.showConfirmDialog(this, "Are you sure to exit the game?", "Exit", JOptionPane.YES_NO_OPTION);
       
        if(res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setText("Exit <");
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setText("Exit");
    }//GEN-LAST:event_ExitMouseExited

    private void playBackgroundMusic() {
        MusicThread th = MusicThread.getInstance();
        th.startMusic("./src/darkinsrevenge/Resources/bgmusic.wav");
        th.start();
    }
    
    public void stopMusic() {
        c.stop();
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Leaderboard;
    private javax.swing.JLabel PlayGame;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
